### ISSUE TITLE
Nouvelle visite V189-9

### ISSUE THREAD

**Issue by l3miage-baht** [grenoble/chamis-de-grenoble#9]
Visite : V189-9
Visiteur : thierno
Visité le : 14/04/2021 18:15
Mode : distanciel
Status : Abandon
Points : 0
Score : 0
Temps : 45mn

Commentaire :
  - Les chamois ça va. Mais il faut encore un tout petit peut plus de temps.
  - Couvre feu oblige j'ai du rentrer sans pachidermes ni écureil aplati dès 19h.
  - Un autre jour pour donner suite

**Comment by xcriptus** [comment]
OK. J'ai dû aussi changer le texte car il est incohérent de dire qu'il à fallu rentrer avant le couvre feu sachat qu'il est mis que la visite est faîte en distanciel. En fait les jeux de tests doivent être cohérents que ca soit sous forme de junit ou de scénarios :-)
